### ISSUE TITLE
typescript error TS2307: Cannot find module './util/bases' or its corresponding type declarations.

### ISSUE THREAD

**Issue by mirceanis** [achingbrain/uint8arrays#23]
I get the error in the title when I try to use this library in a typescript project with the following settings in tsconfig.json

```json
{
  "strict": true,
  "skipLibCheck": false
}
```

Here is a [minimal project](https://gist.github.com/mirceanis/d20d449a4b2c887dee02d954a699ef55) that reproduces the issue when you run `npm install`

It seems to be caused by a mismatch in layout between the source tree and the `dist` file tree.
In `dist/to-string.d.ts`, the `.util/bases` path is no longer valid, it should be `../util.bases`

~~Perhaps this is an aegir bug ( https://github.com/ipfs/aegir/issues/759 https://github.com/ipfs/aegir/issues/849 )~~, but I think it can also be worked around if the source files are moved to a `src/` folder instead of the root dir. That should keep the path consistent in both source and dist situations.

Edit:
It seems the files are placed correctly by `aegir` but are excluded from packing by the very strict `files` entry in `package.json`.

Edit:
This bug has been introduced in 99c8aaa so it affects versions 2.1.6 & 2.1.7
